receivers:
  dynatrace:
    API_ENDPOINT: ${env:API_ENDPOINT}
    API_TOKEN: ${env:API_TOKEN}
    metric_selectors:
      - builtin:containers.cpu.usageTime
      - builtin:containers.memory.residentSetBytes
      - builtin:host.disk.writeTime
      - builtin:host.disk.readTime
      - builtin:host.disk.used
      - builtin:host.disk.avail
      - builtin:host.net.nic.trafficOut
      - builtin:host.net.nic.trafficIn 
      - builtin:kubernetes.node.conditions
    resolution: 1m
    from: now-1m
    to: now
    poll_interval: 30s 
    max_retries: 3
    http_timeout: 30s

exporters:
  otlphttp:
    endpoint: http://localhost:4318  

processors:
  batch:
  resource:
    attributes:
      - key: environment
        value: ${env:DEPLOYMENT_ENVIRONMENT}  # prod, stage, test, dev
        action: upsert
      - key: project_name
        value: ${env:PROJECT_NAME}            # inject your project/cluster name dynamically
        action: upsert
      - key: team_owner
        value: "team-sid"
        action: insert

service:
  pipelines:
    metrics:
      receivers: [dynatrace]
      processors: [resource, batch]
      exporters: [otlphttp]

